version: 0.0.{build}

skip_tags: true

image:
- Visual Studio 2017
- ubuntu1804

configuration: Release
platform: x64

# environment
for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  environment:
    qt: 5.12
    arch: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    cc: VS2017
    QTDIR: C:\Qt\5.12\msvc2017_64
-
  matrix:
    only:
      - image: ubuntu1804
  environment:
    APPVEYOR_BUILD_WORKER_IMAGE: ubuntu1804
    cc: gcc

install:
- sh: sudo apt-get update -qq
- sh: sudo apt-get install -qq qt5-default qtmultimedia5-dev
- sh: sudo apt-get install -qq libglu1-mesa-dev
- sh: sudo apt-get install -qq libevdev-dev
before_build:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch%

build_script:
- sh: qmake -v
- sh: cd DobieStation 
- sh: qmake DobieStation.pro
- sh: make
- cmd: msbuild "C:\projects\dobiestation\DobieStation\DobieStation.sln" /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
- cmd: 7z a -xr!*.lib DobieStation.zip build/bin/
- sh: 7z a ../DobieStation.zip DobieStation

test: off

artifacts:
- path: DobieStation.zip
  type: WebDeployPackage
