version: 0.0.{build}

skip_tags: true

skip_commits:
  files:
    - .github/*
    - .github/*/*
    - README.md

image:
  - Visual Studio 2019
  - Ubuntu1804

configuration: Release Optimized

platform: x64

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  environment:
    qt: 5.14.0
    arch: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    cc: VS2019
    QTDIR: C:\Qt\5.14.0\msvc2017_64

  build:
    parallel: true
    project: DobieStation\DobieStation.sln

  after_build:
    - 7z a -xr!*.lib DobieStation.zip .\build\bin\* LICENSE
-
  matrix:
    only:
      - image: Ubuntu1804
  environment:
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
    cc: gcc

  install:
    - |-
      sudo apt-get update -qq
      sudo apt-get install -qq qt5-default qtmultimedia5-dev libglu1-mesa-dev

  build_script:
    - |-
      qmake -v
      cd DobieStation
      qmake DobieStation.pro
      make -j$(nproc)
      cd $APPVEYOR_BUILD_FOLDER

  after_build:
    - 7z a DobieStation.zip ./DobieStation/DobieStation LICENSE

test: off

artifacts:
  - path: DobieStation.zip
