INSTR(Null)
INSTR(LoadConst)
INSTR(LoadFloatConst)

INSTR(LoadInt)
INSTR(LoadQuad)
INSTR(StoreQuad)
INSTR(LoadQuadInc)
INSTR(StoreQuadInc)

INSTR(MoveIntReg)

INSTR(ShiftLeft)
INSTR(AddIntReg)
INSTR(AddIntRegReg)
INSTR(AddUnsignedImm)

INSTR(Jump)
INSTR(JumpIndirect)
INSTR(JumpAndLink)
INSTR(JumpAndLinkIndirect)

INSTR(BranchEqual)
INSTR(BranchNotEqual)
INSTR(BranchGreater)
INSTR(BranchGreaterOrEqual)

INSTR(VMulVectorByScalar)
INSTR(VMaddVectorByScalar)

INSTR(SetClipFlags)

INSTR(MoveXTOP)
INSTR(MoveXITOP)
INSTR(Stop)
