INSTR(Null)
INSTR(LoadConst)
INSTR(LoadFloatConst)

INSTR(LoadInt)
INSTR(LoadQuad)
INSTR(StoreQuad)
INSTR(LoadQuadInc)
INSTR(StoreQuadInc)

INSTR(MoveIntReg)

INSTR(ShiftLeft)
INSTR(AddIntReg)
INSTR(AddUnsignedImm)

INSTR(Jump)
INSTR(JumpIndirect)
INSTR(JumpAndLink)
INSTR(JumpAndLinkIndirect)

INSTR(BranchEqual)
INSTR(BranchNotEqual)
INSTR(BranchGreater)
INSTR(BranchGreaterOrEqual)

INSTR(VAddVectorByScalar)
INSTR(VAddVectors)
INSTR(VMulVectorByScalar)
INSTR(VMulVectors)
INSTR(VMaddVectorByScalar)
INSTR(VMaddAccByScalar)
INSTR(VDiv)

INSTR(VFloatToFixed0)
INSTR(VFloatToFixed4)

INSTR(SetClipFlags)
INSTR(UpdateMacFlags)

INSTR(StallQPipeline)
INSTR(UpdateMacPipeline)
INSTR(MoveXTOP)
INSTR(MoveXITOP)
INSTR(Xgkick)
INSTR(Stop)
